[package]
name = "event_behavior_tree"
version = "0.1.0"
authors = ["fnzr <5471818+fnzr@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
